[tox]
envlist = py311, py312

[testenv]
extras = test
commands = pytest -v tests/
setenv =
    PYTHONPATH = {toxinidir}

[testenv:lint]
extras = dev
commands =
    ruff check qiskit_waveform_sim tests
    black --check qiskit_waveform_sim tests
    mypy qiskit_waveform_sim

[testenv:docs]
extras = docs
commands =
    sphinx-build -b html docs/source docs/_build/html